async (page) => {
  const desktop = await page.context().browser().browserType().connectOverCDP('http://127.0.0.1:9337')
  const context = desktop.contexts()[0]; context.setDefaultTimeout(12000)
  const island = context.pages().find(p => p.url().includes('window=island'))
  const call = (method, ...args) => island.evaluate(async ({method,args}) => {const {api}=await import('/src/lib/api.ts'); return api[method](...args)}, {method,args})
  const info = await call('dataInfo')
  if (!info.path.replaceAll('\\','/').includes('/output/acceptance/profile/')) throw new Error('Refusing non-test database')
  for (const c of await call('listConnections')) await call('removeConnection',c.id)
  const existing=context.pages().find(p=>!p.url().includes('window=')); const created=existing?Promise.resolve(existing):context.waitForEvent('page'); await call('menuAction','open_main'); const panel=await created
  await panel.getByRole('button',{name:'设置',exact:true}).click()
  await panel.getByRole('navigation',{name:'设置分区'}).getByRole('button',{name:'连接管理',exact:true}).click()
  await panel.getByRole('button',{name:'添加连接',exact:true}).click()
  await panel.getByRole('button',{name:'下一步',exact:true}).click()
  await panel.getByRole('button',{name:/^API Key/}).click()
  await panel.getByRole('button',{name:'下一步',exact:true}).click()
  await panel.getByLabel('连接名称（选填）',{exact:true}).fill('验收钱包连接')
  // 隔离验收禁止读取真实凭证：UI 走到读取必然报隔离错误，实际插入改走显式测试凭证的 API
  await panel.getByRole('button',{name:'读取并添加',exact:true}).click()
  await panel.getByRole('alert').filter({hasText:'隔离验收'}).waitFor()
  await panel.getByRole('button',{name:'上一步',exact:true}).click()
  await panel.getByRole('button',{name:'上一步',exact:true}).click()
  await panel.getByRole('button',{name:'取消',exact:true}).click()
  await panel.getByRole('dialog').waitFor({state:'hidden'})
  await call('addConnection',{platform:'claude',kind:'api',name:'验收钱包连接',secret:'test-valid',base_url:'http://127.0.0.1:18765'})
  const [connection]=await call('listConnections'); if(!connection)throw new Error('Add failed')
  if(connection.name!=='验收钱包连接')throw new Error('Custom name not applied')
  await call('setIslandConnection',connection.id)
  const balance=await call('connectionBalance',connection.id,true); if(balance.state!=='ok'||balance.balance!==12.5)throw new Error('Wrong balance')
  await panel.getByRole('button',{name:'断开',exact:true}).filter({visible:true}).click()
  await panel.getByRole('button',{name:'重新连接',exact:true}).filter({visible:true}).waitFor()
  if ((await call('listConnections'))[0].status !== 'paused') throw Error('Pause was not persisted')
  let blocked = false; try { await call('connectionBalance',connection.id,true) } catch { blocked = true }
  if (!blocked) throw Error('Paused connection queried remotely')
  await panel.getByRole('button',{name:'重新连接',exact:true}).filter({visible:true}).click()
  await panel.getByRole('button',{name:'断开',exact:true}).filter({visible:true}).waitFor()
  await panel.getByRole('button',{name:'编辑',exact:true}).filter({visible:true}).click()
  await panel.getByLabel('连接名称',{exact:true}).fill('验收钱包连接改名')
  await panel.getByLabel('新的 API Key（选填）',{exact:true}).fill('test-zero')
  await panel.getByRole('button',{name:'保存',exact:true}).click()
  await panel.getByRole('dialog').waitFor({state:'hidden'})
  if ((await call('listConnections'))[0].name !== '验收钱包连接改名') throw new Error('Rename not persisted')
  const zero=await call('connectionBalance',connection.id,true);if(zero.state!=='ok'||zero.balance!==0)throw new Error('Zero lost or old cache retained')
  await panel.locator('input[type=file]').setInputFiles('output/acceptance/import.json')
  await panel.getByText('导入完成：更新 2 条请求、1 条会话标题',{exact:true}).waitFor()
  const second=await call('importData',await call('exportData',null));if(second.requests_changed!==0)throw new Error('Import not deduplicated')
  const exported=JSON.parse(await call('exportData',null));if(exported.requests.length!==2||JSON.stringify(exported).includes('test-zero'))throw new Error('Export incorrect or secret included')
  await panel.getByRole('button',{name:'历史保留时间',exact:true}).click()
  await panel.getByRole('menuitemradio',{name:'保留 30 天',exact:true}).click()
  await panel.getByRole('button',{name:'预览',exact:true}).click()
  await panel.getByRole('alertdialog',{name:'确认历史清理'}).waitFor()
  await panel.getByRole('button',{name:'确认清理',exact:true}).click()
  await panel.getByText('已清理 1 条请求记录',{exact:true}).waitFor()
  if(JSON.parse(await call('exportData',null)).requests.length!==1)throw new Error('Cleanup wrong range')
  await panel.getByRole('button',{name:'移除',exact:true}).filter({visible:true}).click()
  await panel.getByRole('dialog').getByRole('button',{name:'移除',exact:true}).click()
  await panel.getByRole('dialog').waitFor({state:'hidden'})
  if((await call('listConnections')).length!==0)throw new Error('Remove failed')
  if(JSON.parse(await call('exportData',null)).requests.length!==1)throw new Error('Connection removal deleted history')
  await panel.screenshot({path:'output/acceptance/data-flow.png'})
  await call('setRetentionDays',null)
  await panel.getByRole('button',{name:'关闭主面板',exact:true}).click()
  return {pass:true,checks:['UI add name field + isolated read blocked as designed','named insert via API','selection','balance','pause blocks queries','reconnect retains credentials','rename persists','replace key/cache invalidation','zero balance','UI import','deduplication','credential-free export','UI cleanup preview/confirm','UI remove preserves history']}
}
